"""Human corrections to renewal data — the rules, in one place.

Nothing in the renewal worklist is typed by a person. Candidates are rebuilt
from the live book every night by ``candidate_refresh``, and project_85_renewals
is re-projected from them. So a fix written straight onto a row is gone by
morning, and the number it fed — premium, urgency, the strategy note, the whole
retention picture — quietly reverts with it. That is the reason a wrong premium
in this system stays wrong.

A correction is therefore recorded as a ``portal_overrides`` row keyed by a
NATURAL key that survives a rebuild, and applied in two places: on read, so the
CRM is right the moment you save, and inside the refresh, so the rebuild carries
the correction forward instead of undoing it. The value is also written straight
onto the row, so everything reading Supabase directly agrees today rather than
after the next refresh.

Two surfaces, because the renewal desk works one and the engine owns the other:

* ``PROJECTION`` — ``project_85_renewals``, keyed by policy_number. What the CRM
  card edits.
* ``CANDIDATES`` — ``renewal_candidates``, keyed by the event identity the
  refresh upserts on (``insured_id | policy_lineage_id | renewal_event_date``).
  The ledger the projection is built from.

Removing a renewal runs through the same mechanism rather than a DELETE. The
same policy would rebuild the same candidate tomorrow, and renewal_actions
cascades off the projection row — deleting one erases the history of the work
that was done on it. What a person actually means is "this is not a renewal I
have to work", so that is what gets recorded, on both surfaces, reversibly.

Identity and derived fields are never correctable: policy identifiers are how a
row is matched back to the AMS and to its own lineage, and
``increase_percentage`` is generated by Postgres from the two premiums — fix
those and the change follows.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date
from typing import TYPE_CHECKING, Any, Mapping

from hermes.operations.renewal_tracker import VALID_RISK_STATUSES

from . import eligibility as elig

if TYPE_CHECKING:
    from hermes_integrations.supabase_client import SupabaseClient

log = logging.getLogger(__name__)

KEY_FIELD = "renewal_key"          # candidate natural key, carried on API rows
KEY_SEP = "|"

FIELD_TEXT, FIELD_NUMBER, FIELD_DATE, FIELD_ENUM = "text", "number", "date", "enum"


@dataclass(frozen=True)
class Surface:
    """A correctable renewal table: what identifies a row, what may be changed,
    and how a row is taken off the worklist."""
    entity_type: str
    key_field: str
    editable: Mapping[str, str]
    dismiss_field: str
    dismiss_value: Any


# The renewal desk's working copy. ``dismissed`` is not a column — an override on
# a field the table does not carry is still applied on read, which is exactly the
# soft-delete this needs and costs no migration.
PROJECTION = Surface(
    entity_type="project_85_renewals",
    key_field="policy_number",
    editable={
        "client_name": FIELD_TEXT,
        "premium_current": FIELD_NUMBER,
        "premium_renewal": FIELD_NUMBER,
        "risk_status": FIELD_ENUM,
        "expiration_date": FIELD_DATE,
        "last_contact_date": FIELD_DATE,
        "ai_strategy_notes": FIELD_TEXT,
    },
    dismiss_field="dismissed",
    dismiss_value=True,
)

# The event ledger underneath it.
CANDIDATES = Surface(
    entity_type="renewal_candidates",
    key_field=KEY_FIELD,
    editable={
        "client_name": FIELD_TEXT,
        "line_of_business": FIELD_TEXT,
        "premium_current": FIELD_NUMBER,
        "premium_renewal": FIELD_NUMBER,
        "risk_status": FIELD_ENUM,
        "expiration_date": FIELD_DATE,
    },
    dismiss_field="eligibility_state",
    dismiss_value=elig.STATE_EXCLUDED,
)


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------
def candidate_key(row: dict[str, Any]) -> str:
    """A renewal event's natural key — the refresh's own conflict target."""
    return KEY_SEP.join((
        str(row.get("insured_id") or "").strip(),
        str(row.get("policy_lineage_id") or "").strip(),
        str(row.get("renewal_event_date") or "")[:10],
    ))


def split_key(key: str) -> tuple[str, str, str]:
    """Natural key -> the identity triple.

    Split from both ends, not by counting separators: the lineage id in the
    middle is itself a composite (``insured:lob:root``) built from a policy
    number nobody controls.
    """
    if key.count(KEY_SEP) < 2:
        raise ValueError(f"malformed renewal key: {key!r}")
    insured, rest = key.split(KEY_SEP, 1)
    lineage, event_date = rest.rsplit(KEY_SEP, 1)
    return insured, lineage, event_date


def key_filters(key: str) -> dict[str, str]:
    """PostgREST filters that select exactly the candidate a key names."""
    insured, lineage, event_date = split_key(key)
    return {
        "insured_id": f"eq.{insured}",
        "policy_lineage_id": f"eq.{lineage}",
        "renewal_event_date": f"eq.{event_date}",
    }


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
def coerce(surface: Surface, field_name: str, value: Any) -> Any:
    """Read a submitted correction, or say why it isn't one.

    Raises ValueError with a message meant for the person who typed it.
    """
    field_name = (field_name or "").strip()
    kind = surface.editable.get(field_name)
    if kind is None:
        raise ValueError(
            f"{field_name!r} is not correctable; allowed: {sorted(surface.editable)}"
        )

    if value is None or (isinstance(value, str) and not value.strip()):
        # Clearing a field is a real correction — a premium the AMS invented, a
        # renewal number that turned out not to exist.
        return None

    if kind == FIELD_NUMBER:
        try:
            return float(value)
        except (TypeError, ValueError):
            raise ValueError(f"{field_name} must be a number, got {value!r}")

    if kind == FIELD_DATE:
        text = str(value).strip()[:10]
        try:
            date.fromisoformat(text)
        except ValueError:
            raise ValueError(f"{field_name} must be a date (YYYY-MM-DD), got {value!r}")
        return text

    if kind == FIELD_ENUM:      # risk_status — a Postgres enum, in caps
        text = str(value).strip().upper()
        if text not in VALID_RISK_STATUSES:
            raise ValueError(
                f"unknown risk_status {text!r}; must be one of {list(VALID_RISK_STATUSES)}"
            )
        return text

    return str(value).strip()


# ---------------------------------------------------------------------------
# Overlay
# ---------------------------------------------------------------------------
def with_keys(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Copies of candidate *rows* carrying their natural key, ready to overlay."""
    return [dict(r, **{KEY_FIELD: candidate_key(r)}) for r in rows]


def strip_keys(row: dict[str, Any]) -> dict[str, Any]:
    """Drop the fields that exist for the overlay, not for the table."""
    return {k: v for k, v in row.items()
            if k not in (KEY_FIELD, "_overridden", PROJECTION.dismiss_field)}


def is_dismissed(surface: Surface, row: dict[str, Any]) -> bool:
    """Has a human taken this renewal off the worklist?"""
    return row.get(surface.dismiss_field) == surface.dismiss_value


def apply(
    supa: "SupabaseClient", rows: list[dict[str, Any]], *, surface: Surface = PROJECTION
) -> list[dict[str, Any]]:
    """Overlay active corrections onto renewal rows.

    Best-effort: a correction is an enrichment, and losing the overrides table
    must not take the renewal worklist down with it.
    """
    from hermes.overrides.core import apply_overrides
    from hermes.overrides.store import active_overrides

    keyed = with_keys(rows) if surface is CANDIDATES else rows
    try:
        ovr = active_overrides(supa, surface.entity_type)
    except Exception:  # noqa: BLE001
        log.exception("renewal corrections lookup failed; serving uncorrected")
        return keyed
    if not ovr:
        return keyed
    return apply_overrides(
        keyed, ovr, entity_type=surface.entity_type, key_field=surface.key_field
    )
