#!/usr/bin/env python3
"""Regenerate the Live runtime tools table in docs/hermes-tool-map.md.

Reads tool names and descriptions from GET /api/command-center/skills (same JSON
as the Command Center skills panel). Falls back to hermes.agent.skills_catalog
when the API is not reachable — useful offline and in CI.

Usage:
    python scripts/gen_tool_map.py              # update docs/hermes-tool-map.md
    python scripts/gen_tool_map.py --check      # exit 1 if the doc would change
    python scripts/gen_tool_map.py --offline    # skip HTTP; import catalog directly
    python scripts/gen_tool_map.py --url http://127.0.0.1:8787/api/command-center/skills

Run from repo root with the venv active (or PYTHONPATH=packages/rsg-hermes-core:.).
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DOC = REPO_ROOT / "docs" / "hermes-tool-map.md"
DEFAULT_URL = "http://127.0.0.1:8787/api/command-center/skills"

BEGIN_MARKER = "<!-- LIVE_RUNTIME_TOOLS_BEGIN -->"
END_MARKER = "<!-- LIVE_RUNTIME_TOOLS_END -->"

# Data/backend source for each runtime tool — derived from hermes/agent/nl_agent.py
# handlers. Update when a tool's backing store changes.
TOOL_SOURCES: dict[str, str] = {
    "ams_client_snapshot": "NowCerts (live AMS)",
    "appointments_by_line": "Supabase (`carriers`)",
    "case_progress": "Supabase (`agency_crm_*`, legacy → Zoho)",
    "client_documents": "Nextcloud",
    "client_policies": "Canonical book (Supabase, NowCerts-sourced)",
    "commission_shortfalls": "Supabase (`commission_ledger`)",
    "commission_summary": "Supabase (`commission_ledger`)",
    "crm_client_activity": "Supabase (`agency_crm_*`, legacy → Zoho)",
    "email_search": "Microsoft 365 Graph",
    "find_client": "Canonical book (Supabase, NowCerts-sourced)",
    "investigate_policy": "NowCerts + Supabase mirror + renewals (read-only)",
    "book_sync_health": "Supabase canonical book sync health",
    "intake_lead": "Supabase intake; Zoho CRM when `HERMES_WRITE_TO_ZOHO`",
    "list_carriers": "Supabase (`carriers`)",
    "list_cases": "Supabase (`agency_crm_*`, legacy → Zoho)",
    "list_intake_submissions": "Supabase (`intake_submissions`)",
    "list_skills": "Hermes catalog (meta)",
    "lookup_class_code": "Supabase (`gl_class_codes`, `wc_class_codes`)",
    "match_carrier_appetite": "Supabase (`carrier_appetite`)",
    "renewals_overview": "Supabase (`project_85_renewals`)",
    "run_report": "Supabase + Hermes report dispatcher",
    "web_research": "Public web",
}


def _fetch_catalog(url: str, timeout: float) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"GET {url} failed: {exc}") from exc


def _catalog_offline() -> dict[str, Any]:
    from hermes.agent.skills_catalog import catalog

    return catalog()


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _render_table(runtime_tools: list[dict[str, str]]) -> str:
    lines = [
        "| Tool | Source | Description |",
        "| --- | --- | --- |",
    ]
    for tool in sorted(runtime_tools, key=lambda t: t.get("name", "")):
        name = _escape_cell(tool.get("name") or "?")
        source = _escape_cell(TOOL_SOURCES.get(name, "—"))
        desc = _escape_cell(tool.get("description") or "")
        lines.append(f"| `{name}` | {source} | {desc} |")
    return "\n".join(lines)


def _build_generated_block(runtime_tools: list[dict[str, str]]) -> str:
    count = len(runtime_tools)
    header = (
        f"_Regenerated by `scripts/gen_tool_map.py` from "
        f"`GET /api/command-center/skills` — {count} tools. Do not edit by hand._"
    )
    return f"{header}\n\n{_render_table(runtime_tools)}"


def _replace_between_markers(doc_text: str, new_block: str) -> str:
    if BEGIN_MARKER not in doc_text or END_MARKER not in doc_text:
        raise ValueError(
            f"Markers missing in doc — expected {BEGIN_MARKER} and {END_MARKER}"
        )
    before, rest = doc_text.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return f"{before}{BEGIN_MARKER}\n{new_block}\n{END_MARKER}{after}"


def _load_catalog(url: str, offline: bool, timeout: float) -> dict[str, Any]:
    if offline:
        return _catalog_offline()
    try:
        return _fetch_catalog(url, timeout)
    except RuntimeError:
        print("warning: API unreachable — falling back to offline catalog()", file=sys.stderr)
        return _catalog_offline()


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate the Hermes live runtime tools table.")
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC, help="Markdown file with markers")
    parser.add_argument("--url", default=DEFAULT_URL, help="Skills API URL")
    parser.add_argument("--timeout", type=float, default=5.0, help="HTTP timeout seconds")
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Import hermes.agent.skills_catalog instead of HTTP",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the doc is stale (no write)",
    )
    args = parser.parse_args()

    doc_path = args.doc.resolve()
    if not doc_path.is_file():
        print(f"error: doc not found: {doc_path}", file=sys.stderr)
        return 1

    catalog = _load_catalog(args.url, args.offline, args.timeout)
    runtime_tools = catalog.get("runtime_tools") or []
    if not runtime_tools:
        print("error: catalog has no runtime_tools", file=sys.stderr)
        return 1

    names = {t.get("name") for t in runtime_tools}
    missing_sources = sorted(n for n in names if n and n not in TOOL_SOURCES)
    if missing_sources:
        print(
            f"error: add TOOL_SOURCES entries for: {', '.join(missing_sources)}",
            file=sys.stderr,
        )
        return 1

    new_block = _build_generated_block(runtime_tools)
    old_text = doc_path.read_text(encoding="utf-8")
    new_text = _replace_between_markers(old_text, new_block)

    if new_text == old_text:
        print(f"ok: {doc_path} is up to date ({len(runtime_tools)} tools)")
        return 0

    if args.check:
        print(f"stale: {doc_path} differs from catalog ({len(runtime_tools)} tools)", file=sys.stderr)
        return 1

    doc_path.write_text(new_text, encoding="utf-8")
    print(f"updated: {doc_path} ({len(runtime_tools)} tools)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
